spring:
  application:
     name: message
  redis:
    port: 6379
    host: 101.201.147.153
    password:
server:
  port: 6060
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true



